let tempDatabase = [
  {
    id: 1,
    name: "0000only murders in the building",
    nameFa: "اسب های کودن",
    nameUrl: "0000only-murders-in-the-building",
    year: "2021",
    imdb: 8.1,
    imdbVoteCount: 78000,
    avaRating: 9.2,
    avaVoteCount: 35,
    metacritic: 82,
    rotten: 98,
    cover: "public/assets/Only-Murders-in-the-Building.jpg",
    bgCover: "public/assets/w3HCVSgWyHgm60r0raQQWyqOv5u-1024x576.jpg",
    postScript: "فصل ۰۴ - قسمت ۰۳ اضافه شد",
    description:
      "داستان سریال در مورد سه غریبه است که ویژگی مشترکشان علاقه به جنایتهای واقعی است که خودشان را ناگهان درگیر یک پرونده واقعی می بینند...",
    isSeries: true,
    hasDub: true,
    hasSub: true,
    hasOnline: true,
    genres: ["جنایی", "درام", "کمدی"],
  },
  {
    id: 2,
    name: "1111only murders in the building",
    nameFa: "اسب های کودن",
    nameUrl: "1111only-murders-in-the-building",
    year: "2021",
    imdb: 8.1,
    imdbVoteCount: 78000,
    avaRating: 9.2,
    avaVoteCount: 35,
    metacritic: 82,
    rotten: 98,
    cover: "public/assets/Only-Murders-in-the-Building.jpg",
    bgCover: "public/assets/w3HCVSgWyHgm60r0raQQWyqOv5u-1024x576.jpg",
    postScript: "فصل ۰۴ - قسمت ۰۳ اضافه شد",
    description:
      "داستان سریال در مورد سه غریبه است که ویژگی مشترکشان علاقه به جنایتهای واقعی است که خودشان را ناگهان درگیر یک پرونده واقعی می بینند...",
    isSeries: false,
    hasDub: true,
    hasSub: true,
    hasOnline: true,
    genres: ["جنایی", "درام", "کمدی"],
  },
  {
    id: 3,
    name: "2222only murders in the building",
    nameFa: "اسب های کودن",
    nameUrl: "2222only-murders-in-the-building",
    year: "2021",
    imdb: 8.1,
    imdbVoteCount: 78000,
    avaRating: 9.2,
    avaVoteCount: 35,
    metacritic: 82,
    rotten: 98,
    cover: "public/assets/Only-Murders-in-the-Building.jpg",
    bgCover: "public/assets/w3HCVSgWyHgm60r0raQQWyqOv5u-1024x576.jpg",
    postScript: "",
    description:
      "داستان سریال در مورد سه غریبه است که ویژگی مشترکشان علاقه به جنایتهای واقعی است که خودشان را ناگهان درگیر یک پرونده واقعی می بینند...",
    isSeries: true,
    hasDub: true,
    hasSub: true,
    hasOnline: true,
    genres: ["جنایی", "درام", "کمدی"],
  },
];
export default tempDatabase;
